package object common {

  val NOVA_CITIES = List(
    "Arlington",
    "Fairfax",
    "Alexandria",
    "Reston",
    "Herndon",
    "Vienna",
    "Great Falls",
    "Falls Church",
    "Oakton",
    "Chantilly",
    "Centreville",
    "McLean",
    "Burke",
    "Clifton",
    "Lorton",
    "Fairfax Station",
    "Baileys Crossroads",
    "Fort Belvoir",
    "Sterling",
    "Ashburn",
    "Leesburg",
    "Hamilton",
    "Brambleton",
    "Purcellville",
    "Stone Ridge",
    "South Riding",
    "Middleburg",
    "Aldie",
    "Round Hill",
    "Upperville",
    "Lovettesville",
    "Bluemont",
    "Paris",
    "Waterford",
    "Hillsboro",
    "Woodbridge",
    "Gainesville",
    "Bristow",
    "Haymarket",
    "Occoquan",
    "Dumfries",
    "Dale City",
    "Nokesville",
    "Manassas"
  )

}
